---
 - hosts: DB
   become: true
   tasks:
     - name: Install tools
       apt: name={{item}} state=present update_cache=yes
       with_items:
        - python-mysqldb

     - name: Install mysql
       apt: name=mysql-server state=present update_cache=yes

     - name: Ensure mysql is started
       service: name=mysql state=started enabled=yes

     - name: Ensure mysql listens on all ports
       lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address=0.0.0.0"
       notify: restart mysql

     - name: Create demodb
       mysql_db: name=demo state=present

     - name: Create mysql demouser
       mysql_user: name=demo password=demo priv=demo.*:ALL host="%" state=present

   handlers:
     - name: restart mysql
       service: name=mysql state=restarted
